is.installed <- function(mypkg) is.element(mypkg, installed.packages()[,1])

if (!is.installed("pkgload")) install.packages("pkgload")
if (!is.installed("processx"))install.packages("processx")
if (!is.installed("golem")) install.packages("golem")
if (!is.installed("bs4Dash")) install.packages("bs4Dash")
if (!is.installed("DT"))install.packages("DT")
if (!is.installed("BiocManager")) install.packages("BiocManager")
if (!is.installed("mixOmics")) BiocManager::install('mixOmics')
if (!is.installed("rgl"))install.packages("rgl")
if (!is.installed("markdown")) install.packages("markdown")
if (!is.installed("shinybusy")) install.packages("shinybusy")
if (!is.installed("purrr"))install.packages("purrr")
if (!is.installed("visNetwork")) install.packages("visNetwork")
if (!is.installed("shinyjs")) install.packages("shinyjs")
if (!is.installed("shinyalert"))install.packages("shinyalert")
if (!is.installed("shinyWidgets")) install.packages("shinyWidgets")
if (!is.installed("shinyvalidate"))install.packages("shinyvalidate")
if (!is.installed("openxlsx")) install.packages("openxlsx")
if (!is.installed("readxl")) install.packages("readxl")