---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Holomics
Holomics is a R Shiny application, which enables its users to perform single- and multi-omics analyses. Therefore, Holomics provides a user-friendly interface to upload the different datasets, choose and perform the various analyses and then presents the results to the user. To perform the various analyses Holomics uses the R package mixOmics. This means Holomics takes the input files, forwards them to the mixOmics algorithms and takes the resulting plots/tables and presents them to user. 

mixOmics provides numerous analyses algorithms, but Holomics only integrates the two single-omics algorithms "Principle Component Analysis (PCA)" and "Partial Least Squares Discriminant Analysis (PLS-DA)", one pairwise omics analysis called "sparse Partial Least Squares (sPLS)" and one multi-omics analysis called "Data Integration Analysis for Biomarker discovery using Latent variable approaches for Omics studies (DIABLO)".

## Install Holomics
<!-- TODO -->

## Further information
For further information on how to use Holomics please take a look at our vignette.